minimumReleaseAgeExclude:
  - '@expo/cli@58.0.4'
  - '@expo/devtools@58.0.1'
  - '@expo/dom-webview@58.0.1'
  - '@expo/image-utils@0.12.1'
  - '@expo/log-box@58.0.4'
  - '@expo/metro-config@58.0.4'
  - '@expo/prebuild-config@58.0.3'
  - '@expo/router-server@58.0.3'
  - babel-preset-expo@58.0.4
  - expo-asset@58.0.4
  - expo-constants@58.0.4
  - expo-font@58.0.2
  - expo-keep-awake@58.0.1
  - expo-modules-autolinking@58.0.3
  - expo-modules-core@58.0.4
  - expo-modules-jsi@58.0.3
  - expo-server@58.0.1
  - expo@58.0.0-preview.4
  - '@expo/metro-runtime@58.0.4'
  - '@expo/ui@58.0.4'
  - expo-audio@58.0.1
  - expo-blur@58.0.1
  - expo-build-properties@58.0.4
  - expo-dev-client@58.0.4
  - expo-dev-launcher@58.0.4
  - expo-dev-menu@58.0.4
  - expo-device@58.0.1
  - expo-glass-effect@58.0.1
  - expo-image@58.0.3
  - expo-linking@58.0.4
  - expo-localization@58.0.1
  - expo-notifications@58.0.4
  - expo-router@58.0.5
  - expo-splash-screen@58.0.1
  - expo-status-bar@58.0.1
  - expo-symbols@58.0.2
  - expo-system-ui@58.0.2
  - expo-web-browser@58.0.1
  - jest-expo@58.0.3
overrides:
  '@xmldom/xmldom@>=0.7.0 <=0.8.14': ^0.8.15
  '@xmldom/xmldom@>=0.9.0-beta.1 <=0.9.11': ^0.9.12
  decode-uri-component@<=0.4.2: ^0.5.0
  uuid@<11.1.1: ^11.1.1
patchedDependencies:
  expo-modules-jsi@58.0.3: patches/expo-modules-jsi@58.0.3.patch
