// Token values transcribed verbatim from DESIGN.md's "Aura: Dark" and
// "Aura: Sanctuary" palettes. Keys are the DESIGN.md token names transformed
// to camelCase (see CONTEXT.md's "Theme" entry) — see DESIGN.md for the
// canonical kebab-case names if you need to cross-reference.

export const auraDarkColors = {
  surface: "#12121d",
  surfaceDim: "#12121d",
  surfaceBright: "#383845",
  surfaceContainerLowest: "#0d0d18",
  surfaceContainerLow: "#1b1a26",
  surfaceContainer: "#1f1e2a",
  surfaceContainerHigh: "#292935",
  surfaceContainerHighest: "#343440",
  surfaceVariant: "#343440",
  surfaceTint: "#c2c2f2",
  inverseSurface: "#e3e0f1",
  inverseOnSurface: "#302f3b",

  primary: "#c2c2f2",
  onPrimary: "#2b2d53",
  primaryContainer: "#1a1b41",
  onPrimaryContainer: "#8283af",
  inversePrimary: "#5a5b84",
  primaryFixed: "#e1e0ff",
  primaryFixedDim: "#c2c2f2",
  onPrimaryFixed: "#16173d",
  onPrimaryFixedVariant: "#42436b",

  secondary: "#cdbdff",
  onSecondary: "#352072",
  secondaryContainer: "#4c388a",
  onSecondaryContainer: "#bda8ff",
  secondaryFixed: "#e8deff",
  secondaryFixedDim: "#cdbdff",
  onSecondaryFixed: "#20015d",
  onSecondaryFixedVariant: "#4c388a",

  tertiary: "#b8cac9",
  onTertiary: "#233333",
  tertiaryContainer: "#122222",
  onTertiaryContainer: "#798a8a",
  tertiaryFixed: "#d4e6e5",
  tertiaryFixedDim: "#b8cac9",
  onTertiaryFixed: "#0e1e1e",
  onTertiaryFixedVariant: "#3a4a49",

  error: "#ffb4ab",
  onError: "#690005",
  errorContainer: "#93000a",
  onErrorContainer: "#ffdad6",

  outline: "#918f99",
  outlineVariant: "#47464e",
  background: "#12121d",
  onBackground: "#e3e0f1",
  onSurface: "#e3e0f1",
  onSurfaceVariant: "#c8c5cf",
} as const;

export const auraSanctuaryColors = {
  surface: "#faf8ff",
  surfaceDim: "#dcd8e6",
  surfaceBright: "#faf8ff",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f4f0ff",
  surfaceContainer: "#eeeaff",
  surfaceContainerHigh: "#e8e4fa",
  surfaceContainerHighest: "#e2dff4",
  surfaceVariant: "#e4e0f0",
  surfaceTint: "#5a5b84",
  inverseSurface: "#302f3b",
  inverseOnSurface: "#e3e0f1",

  primary: "#5a5b84",
  onPrimary: "#ffffff",
  primaryContainer: "#c2c2f2",
  onPrimaryContainer: "#16173d",
  inversePrimary: "#c2c2f2",
  primaryFixed: "#e1e0ff",
  primaryFixedDim: "#c2c2f2",
  onPrimaryFixed: "#16173d",
  onPrimaryFixedVariant: "#42436b",

  secondary: "#61549b",
  onSecondary: "#ffffff",
  secondaryContainer: "#e8deff",
  onSecondaryContainer: "#20015d",
  secondaryFixed: "#e8deff",
  secondaryFixedDim: "#cdbdff",
  onSecondaryFixed: "#20015d",
  onSecondaryFixedVariant: "#4c388a",

  tertiary: "#406a69",
  onTertiary: "#ffffff",
  tertiaryContainer: "#d4e6e5",
  onTertiaryContainer: "#0e1e1e",
  tertiaryFixed: "#d4e6e5",
  tertiaryFixedDim: "#b8cac9",
  onTertiaryFixed: "#0e1e1e",
  onTertiaryFixedVariant: "#3a4a49",

  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  onErrorContainer: "#410002",

  outline: "#767680",
  outlineVariant: "#c5c5d0",
  background: "#faf8ff",
  onBackground: "#1b1b21",
  onSurface: "#1b1b21",
  onSurfaceVariant: "#474651",
} as const;
