name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: yarn
      - run: pnpm install --frozen-lockfile
      - run: eas build --platform android --profile production --non-interactive --no-wait

  build_ios:
    name: Build iOS App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: yarn
      - run: pnpm install --frozen-lockfile
      - run: eas build --platform ios --profile production --non-interactive --no-wait
